# Generated by Django 4.0.5 on 2022-06-22 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jaime',
            old_name='dirección',
            new_name='direccion',
        ),
    ]
